wandb_version: 1

L2_regularization:
  desc: null
  value: 0.01
activation_function:
  desc: null
  value: Sigmoid
batch_size:
  desc: null
  value: 100
drop_out:
  desc: null
  value: 1.0
elapsed_time:
  desc: null
  value: 2304.6382508277893
epoch:
  desc: null
  value: 150
hidden_layers:
  desc: null
  value: 4
hidden_neurons:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 5.0e-05
num_input:
  desc: null
  value: 36
num_output:
  desc: null
  value: 2
total_batch:
  desc: null
  value: 1337
training_episode:
  desc: null
  value: 1200
