wandb_version: 1

L2_regularization:
  desc: null
  value: 0.0
activation_function:
  desc: null
  value: ReLU
batch_size:
  desc: null
  value: 100
drop_out:
  desc: null
  value: 1.0
epoch:
  desc: null
  value: 1000
hidden_layers_1st:
  desc: null
  value: 5
hidden_layers_2nd:
  desc: null
  value: 3
hidden_neurons_1st:
  desc: null
  value: 80
hidden_neurons_2nd:
  desc: null
  value: 40
learning_rate_1st:
  desc: null
  value: 1.0e-05
learning_rate_2nd:
  desc: null
  value: 1.0e-05
num_input_1st:
  desc: null
  value: 18
num_input_2nd:
  desc: null
  value: 6
num_output_1st:
  desc: null
  value: 6
num_output_2nd:
  desc: null
  value: 2
total_batch:
  desc: null
  value: 1210
training_episode:
  desc: null
  value: 1200
